name: sql-course
channels:
  - conda-forge
dependencies:
  - matplotlib
  - numpy
  - keyring
  - pandas
  - duckdb==0.8.0
  - duckdb-engine==0.9.0
  - python-dotenv
  - pip
  - pip:
    - jupyter-book
    - pkgmt>=0.1.7
