name: sql-course
channels:
  - conda-forge
dependencies:
  - matplotlib
  - numpy
  - keyring
  - pandas
  - duckdb
  - python-dotenv
  - pip
  - ipywidgets
  - pip:
    - jupyter-book
    - pkgmt>=0.1.7
